name: MapS
description: An app to save your location.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.2.0
  flutter_dotenv: ^5.0.2
  geolocator: ^8.0.0  # Check for the latest version on pub.dev
  google_maps_flutter: ^2.0.0  # For displaying Google Maps
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
