name: MapS
description: An app to save your location.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.2.0
  flutter_dotenv: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
